### ISSUE TITLE
Problem deploying OPTIONS endpoints

### ISSUE THREAD

**Issue by atzbert** [joostfarla/serverless-cors-plugin#24] opened 2016-04-14 11:14 UTC
For some reason In get an error when deploying the options  endpoints lately.
No idea why. The error is:

> Serverless:   OPTIONS - someEndpoint: Invalid model name specified: application/json;charset=UTF-8=Empty

**Comment by atzbert** [comment] 2016-04-14 11:19
Apparently it's related to the latest serverless version 0.5.5, rollback to 0.5.3 fixes it

**Comment by joostfarla** [comment] 2016-04-17 09:41
Let me see if I can reproduce the issue on SLS v5.5. Can you provide your `s-function.json` config?

**Comment by cdichiara** [comment] 2016-04-28 00:18
Ran into this problem too ... thought it was because I had deleted the Empty model. I put it back into the API Gateway via the UI, and then the configuration of CORS via the UI started working without an error. But the CORS plugin kept on throwing an error. So I included the "Empty" model in the [models plugin](https://www.npmjs.com/package/serverless-models-plugin) for serverless that Hyperbrain made, and it works.

**Comment by joostfarla** [comment] 2016-05-18 13:12
@cdichiara thanks! That explains a lot. At the moment there's a hardcoded dependency on the `Empty` model. I think I have a clue how to solve this. Will work on it asap!

**Comment by cdichiara** [comment] 2016-05-18 13:55
Oh, you're welcome. :) Thanks for making the great plugin! It saves me a bunch of work.

**Comment by dclaze** [comment] 2016-09-07 06:10
This issue should be resolved with https://github.com/joostfarla/serverless-cors-plugin/pull/27

**Comment by joostfarla** [comment] 2016-09-09 08:41
Fixed in v0.4.2!

**Closed by joostfarla** 2016-09-09 08:41 UTC
